package jef.pathfinding.threats;

import jef.pathfinding.IPathfinderPlayer;

public class ThreatAssessment<T extends IPathfinderPlayer> implements Comparable<ThreatAssessment<T>>
{
	private double threatLevel;
	private T player;

	public ThreatAssessment(T player, double threatLevel)
	{
		super();
		this.player = player;
		this.threatLevel = threatLevel;
	}

	/**
	 * @return The threat level. This number is comparable only to other numbers
	 *         generated by the same assessor of the threat on the same turn. Higher
	 *         numbers always indicate a greater threat even if numbers are negative.
	 */
	public double getThreatLevel()
	{
		return this.threatLevel;
	}

	public T getPlayer()
	{
		return this.player;
	}

	@Override
	public int compareTo(ThreatAssessment<T> o)
	{
		return  -1 * Double.compare(threatLevel, o.threatLevel);
	}

	@Override
	public String toString()
	{
		return this.player + " threatLevel=" + this.threatLevel;
	}

}
